/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (kula-world-)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x00069F60u
#define func_00069F60 BootEntry  /* alias */
